name: "dart-action-for-dio"
description: "Use dart write action"
author: "CaiJingLong"

inputs:
  github-token:
    description: "The GitHub token to use for the action"
    required: true
  pub-credentials-json:
    description: "The pub credentials json"
    required: true
  do-publish:
    description: "Whether to publish the package to pub.dev"
    required: false
    default: 'true'
  do-release:
    description: "Whether to release the package to GitHub"
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - uses: subosito/flutter-action@v2
      name: Install Flutter
      with:
        channel: "stable"
        cache: true
    - name: Show Flutter and dart version
      run: |
        dart --version
        flutter --version
      shell: bash
    - uses: bluefireteam/melos-action@v3
        with:
          run-bootstrap: false
    - name: Check satisfied packages
      run: |
        dart ./scripts/melos_packages.dart
        echo $(cat .melos_packages) >> $GITHUB_ENV
    - name: Melos Bootstrap
      run: melos bootstrap
    - name: Install dependencies
      run: dart pub get
      working-directory: ${{ github.action_path }}
      shell: bash
    - name: Run dart
      run: dart run "${{ github.action_path }}/bin/main.dart"
      shell: bash
      env:
        PERSON_TOKEN: ${{ inputs.github-token }}
        PUB_CREDENTIALS_JSON: ${{ inputs.pub-credentials-json }}
        DO_PUBLISH: ${{ inputs.do-publish }}
        DO_RELEASE: ${{ inputs.do-release }}