name: 'dio-release'
description: 'For release cfug/dio'
author: 'CaiJingLong'
inputs:
  github-token:
    description: 'The GitHub token to use for the action'
    required: true
  pub-credentials-json:
    description: 'The pub credentials json'
    required: true
  dry-run:
    description: 'Default is false, set to true will not publish to pub.dev, just run pub publish --dry-run'
    required: false
    default: 'false'
runs:
  using: 'node16'
  main: 'dist/index.js'
