name: 'dio-release'
description: 'For release cfug/dio'
author: 'CaiJingLong'
inputs:
  github-token:
    description: 'The GitHub token to use for the action'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
