name: 'Issue Comment Actions'
on:
  issue_comment:
    types: [created, edited]
jobs:
  issue_comment:
    runs-on: ubuntu-latest
    steps:
      - name: 'Issue Comment Actions'
        uses: CaiJingLong/dio_issue_release_action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pub-credentials-json: ${{ secrets.PUB_CREDENTIALS_JSON }}
