name: Tag to release
run-name: ${{ github.actor }} to trigger release
on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release
        uses: CaiJingLong/action-version-merge@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
    permissions: # Required, because the action will create a release and branch, so need write permission
      deployments: write
      contents: write
      packages: read
